pageInfo:
  title: Intranet VEM
  description: Central de sistemas internos
  logo: https://cdn-icons-png.flaticon.com/512/1055/1055687.png

appConfig:
  theme: nord
  layout: auto
  iconSize: large
  language: pt-BR
  startingView: default
  defaultOpeningMethod: newtab
  enableSearch: true
  enableFontAwesome: true

sections:

  - name: Administrativo
    icon: fas fa-building
    items:
      - title: Cartão VEM
        icon: favicon
        url: https://cartaovem.com.br/home

  - name: TIC
    icon: fas fa-network-wired
    items:
      - title: Cartão VEM
        icon: favicon
        url: https://cartaovem.com.br/home

  - name: SAC
    icon: fas fa-headset
    items:
      - title: Cartão VEM
        icon: favicon
        url: https://cartaovem.com.br/home

  - name: Rodoviario
    icon: fas fa-bus
    items:
      - title: Cartão VEM
        icon: favicon
        url: https://cartaovem.com.br/home

  - name: Bureau
    icon: fas fa-print
    items:
      - title: Cartão VEM
        icon: favicon
        url: https://cartaovem.com.br/home

  - name: Atendimento
    icon: fas fa-users
    items:
      - title: Cartão VEM
        icon: favicon
        url: https://cartaovem.com.br/home

  - name: Supervisão Atendimento
    icon: fas fa-user-tie
    items:
      - title: Cartão VEM
        icon: favicon
        url: https://cartaovem.com.br/home

  - name: Supervisão SAC
    icon: fas fa-user-cog
    items:
      - title: Cartão VEM
        icon: favicon
        url: https://cartaovem.com.br/home

  - name: Livre Acesso
    icon: fas fa-door-open
    items:
      - title: VEM Livre Acesso
        icon: favicon
        url: https://vemlivreacesso.com.br/odin/

  - name: Suporte e Fornecedores
    icon: fas fa-tools
    items:

      - title: VERDANA (Zabbix / Verdanatech)
        icon: fas fa-server
        url: https://atendimento.verdanatech.com

      - title: Contato VERDANA
        icon: fas fa-phone
        url: tel:+558130914252

      - title: Email VERDANA
        icon: fas fa-envelope
        url: mailto:atendimento@verdanatech.com

      - title: PROCENGE (Piramide)
        icon: fas fa-phone
        url: tel:+5581991450999

      - title: SURFIX (Veeam Cloud)
        icon: fas fa-database
        url: https://surfixdatacenter.movidesk.com

      - title: Telefone SURFIX
        icon: fas fa-phone
        url: tel:08000810500

      - title: INORPEL (Firewall)
        icon: fas fa-shield-alt
        url: https://inorpel-cybersecurity.movidesk.com/Account/Login?ReturnUrl=%2f

      - title: Telefone INORPEL
        icon: fas fa-phone
        url: tel:+5583988024263

      - title: HOTLINK (Internet)
        icon: fas fa-wifi
        url: tel:+5581987199315

      - title: POLO IT (Banco de Dados)
        icon: fas fa-database
        url: mailto:dbacenter@polo-it.com.br

      - title: Telefone POLO IT
        icon: fas fa-phone
        url: tel:+557134153050

      - title: Manutenção SEDE - Zé Paulo
        icon: fas fa-tools
        url: tel:+5581997432928
